CREATE TABLE `candidates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`dateOfBirth` varchar(10) NOT NULL,
	`address` text NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(50) NOT NULL,
	`zipCode` varchar(20) NOT NULL,
	`education` varchar(100) NOT NULL,
	`experience` text NOT NULL,
	`languages` text NOT NULL,
	`availability` varchar(100) NOT NULL,
	`tt1Responses` json NOT NULL,
	`tt2Responses` json NOT NULL,
	`tt3Responses` json NOT NULL,
	`tt4Responses` json NOT NULL,
	`tt5Responses` json NOT NULL,
	`tt6Responses` json NOT NULL,
	`tt7Responses` json NOT NULL,
	`empathScore` decimal(10,4) NOT NULL,
	`pioneerScore` decimal(10,4) NOT NULL,
	`mechanistScore` decimal(10,4) NOT NULL,
	`collaboratorScore` decimal(10,4) NOT NULL,
	`nesterScore` decimal(10,4) NOT NULL,
	`profileType` enum('Empath','Pioneer','Mechanist','Collaborator','Nester') NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `candidates_id` PRIMARY KEY(`id`)
);
